web:
  image: nginx:latest
  ports:
    - 80:80
  volumes:
    - .:/var/www/html
    - ./site.conf:/etc/nginx/conf.d/site.conf
  links:
    - php
php:
  container_name: codeeasy-php-container
  build: .
  volumes:
    - .:/var/www/html
  links:
    - mysql
  environment:
    XDEBUG_CONFIG: remote_host=172.17.0.1
mysql:
  image: mariadb:10.0.38
  ports:
    - 8081:3306
  environment:
    MYSQL_ROOT_PASSWORD: root
